"""The two LLM stages of the pipeline: the schema judge, and the text infill.

Both are one prompt and one JSON reply, sent through `ask`. The model only ever
sees data that has been through step 1 or was generated: the judge reads the
anonymized tables, whose names, costs, dates and addresses have all been
replaced, and the infill reads synthetic rows that correspond to no real record.
"""

import json
from pathlib import Path

from pipeline import KEYS, RELATIONS, TEXT

MODEL = "gpt-5.4-mini"
ENV = Path(__file__).resolve().parent / ".env"
BATCH = 25  # Rows per infill request.

# What each table holds, for the infill prompt. Parent tables come first, so a
# child row can be given the name its parent was just assigned.
PURPOSE = {
    "applications": "an application service",
    "components": "one deployed component of an application service",
    "interfaces": "one network interface between two components",
}

JUDGE = """These are anonymized CSV exports of an enterprise architecture landscape. The
names are pseudonyms, so judge the columns by their role, not by their content.

First three rows of each table:
{sample}

Heuristics found these key candidates. A primary key candidate is a column that is present
and unique in every row. A foreign key candidate is a column whose values all appear in
another table's primary key candidate.
{candidates}

More than one candidate can be unique while only one is the identifier of record. Pick the
primary key of each table, and keep only the foreign keys that are real references. Reply as
JSON: {{"primary_keys": {{"table": "column"}}, "foreign_keys": [["table", "column", "parent table"]]}}"""

INFILL = """Write the descriptive text for one table of a synthetic enterprise architecture
landscape. These rows were generated by a relational model; they describe no real system.

Each row of `{table}` is {purpose}. Fill in {columns} for every row: one short sentence in the
register of an architecture inventory, saying what the thing is for. Stay consistent with the
values already in the row and with the names of the related rows, but do not restate them — a
description that reads the row back to itself is useless, and the criticality, cost, date, zone,
protocol and port must not appear in the text. The identifiers are opaque, so never repeat one.
{naming}Do not mention that the data is synthetic.

Rows:
{rows}

Reply as JSON: {{"<{key}>": {{{fields}}}}}, one entry per row and no other keys."""


def ask(prompt):
    """One JSON reply from the model. The API key comes from `.env`."""
    from dotenv import load_dotenv
    from openai import OpenAI, OpenAIError

    load_dotenv(ENV)
    try:
        reply = OpenAI().chat.completions.create(
            model=MODEL,
            reasoning_effort="low",
            response_format={"type": "json_object"},
            messages=[{"role": "user", "content": prompt}],
        )
    except OpenAIError as exc:
        raise RuntimeError(
            f"OpenAI request failed ({type(exc).__name__}); check OPENAI_API_KEY and the network"
        ) from None
    return json.loads(reply.choices[0].message.content)


def judge(tables, candidates, ask=ask):
    """Choose the schema from the heuristic candidates: the LLM judge of Figure 1.

    Uniqueness cannot tell an identifier from a column that happens to be unique
    — `components` has two such columns here — so the choice is the model's, and
    `infer_schema` then checks the answer against the data.
    """
    primary, foreign = candidates
    prompt = JUDGE.format(
        sample=json.dumps({table: rows[:3] for table, rows in tables.items()}, indent=1),
        candidates=json.dumps(
            {
                "primary_key_candidates": primary,
                "foreign_key_candidates": [list(item) for item in foreign],
            },
            indent=1,
        ),
    )
    decision = ask(prompt)
    return {
        "primary_keys": dict(decision["primary_keys"]),
        "foreign_keys": [list(item) for item in decision["foreign_keys"]],
    }


def context(tables, table, row):
    """What the model is shown for one row: its own values, and its parents' names.

    The foreign key is replaced by the name the parent row was given, because the
    alias itself says nothing and the description should read like the landscape.
    """
    item = {key: value for key, value in row.items() if key not in TEXT[table]}
    for child, column, parent in RELATIONS:
        if child == table:
            names = {r[KEYS[parent]]: r["name"] for r in tables[parent]}
            item[column.removesuffix("_id")] = names.get(item.pop(column))
    return item


def infill(tables, ask=ask, batch=BATCH):
    """Fill the free-text columns from the generated rows: the LLM query of Figure 1."""
    result = {table: [dict(row) for row in rows] for table, rows in tables.items()}
    for table, columns in TEXT.items():
        rows, key = result[table], KEYS[table]
        for start in range(0, len(rows), batch):
            chunk = rows[start : start + batch]
            reply = ask(
                INFILL.format(
                    table=table,
                    purpose=PURPOSE[table],
                    columns=" and ".join(f"`{column}`" for column in columns),
                    naming=(
                        "Give every row a distinct, plausible system name; two names must "
                        "differ by more than a trailing letter or number. "
                        if "name" in columns
                        else ""
                    ),
                    rows=json.dumps([context(result, table, row) for row in chunk], indent=1),
                    key=key,
                    fields=", ".join(f'"{column}": "..."' for column in columns),
                )
            )
            for row in chunk:
                for column in columns:
                    text = reply.get(row[key], {}).get(column)
                    if not isinstance(text, str) or not text.strip():
                        raise ValueError(f"No {column} generated for {table} {row[key]}")
                    row[column] = text.strip()
    return result
